### PR TITLE
Ruby on Rails: Forms

### PR DESCRIPTION
**Pull request by franklinben23**
For this project we made a form that creates and updates users using the 3 main existing methods of doing so: the traditional HTML way, the form_tag helper method and the form_with helper method. We also added validations and error handling.

### CODE REVIEW

**Review by oloomoses — CHANGES_REQUESTED** [review]
# Status: Changes Required
#### Hello team, Great job so far. Well done on the readme.
#### Below are some of the changes to be made before the project can be approved :point_down: 
- [x] Kindly ensure that the linter and rubocop are configured correctly and all the checks are passing
- [x] In your commented out `form`, use `users_path` helper for action

Kindly implement the above changes before submitting another code review.
### If you have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help
## HAPPY CODING 
_Slack: Oloo Moses_

**Comment by franklinben23** [comment]
hey @oloomoses  I have a question, how do I use the helper method users_path in the html only form? can you take a look and help me out? or guide to something that will

**Comment by franklinben23** [comment]
want to do that before submitting another

**Review by mke2111 — CHANGES_REQUESTED** [review]
# **STATUS: CHANGES REQUIRED 🔴 ⚠️** 

## Hey, 👋🏽 
 **Thank you for the good job you got going on.**

## REQUIRED CHANGES

- [x] Comment out all the `form` methods except the `form_with` in the form partial, users view.
- [x] Add a `form_for` method in the form partial. This should handle the editing step as required. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/forms/user_form_edit.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/forms))
- [x] In the edit action under users_controller, once an edit is successfully saved, should redirect to `edit_user_path`.


**Kindly make all the requested changes and submit another CRR. 👍🏽** 

## Cheers!! 🍹 & Happy Coding.

# Reach me on slack for a chitchat 🆘  **Roy Mukuye**

**Review by MahmoudBakr23 — CHANGES_REQUESTED** [review]
# **Changes Required 🛑♻**

<hr>

Hello there, good job working on this project and on the requested changes. However, there are still a few more changes to make before moving on. 😊🙏

- [x] Please attach the node_modules folder inside the gitignore file. Currently, there are more than 5k changes on this PR.
- [x] In your README file, kindly add the ```rails db:create```, ```rails db:migrate``` CLIs in the instructions section.

<hr>

Kindly do the required changes and ask for another review 😊
Good luck and happy coding 👨‍💻💻

**Review by Georjane — APPROVED** [review]
## Status: PR Approved 💯 🥇 
### Hi there Team ✋🏽 
Congratulations on successfully completing this project.
You can go ahead and merge this PR. 👍🏽 

_Feel free to reach out to me on Slack if you have any questions, Witah Georjane_ 🤝 
Good luck on your next project and Happy Coding 💻 

**Witah Georjane
Code Reviewer at Microverse Inc
[portfolio](https://witahgeorjane.tech/) | [linkedIn](https://www.linkedin.com/in/witah-georjane/)**

**Pull request merged**
